author:
  name: JAVIERJIA
  role: Module Leader in Innovative Product Development
  bio: Known for Project Supervisor, Former Ubisoft Big Data Product Manager, and Investment & Philosophy.
  location: Chengdu, China

social:
  - id: "x"
    label: "X"
    href: "#_"
  - id: "github"
    label: "GitHub"
    href: "https://github.com/JavierJiaCDUT"
  - id: "linkedin"
    label: "Linkedin"
    href: "#_"
  - id: "email"
    label: "Email"
    href: "mailto:"